### PR TITLE
Added the required native props for EXGLView

### LINKED ISSUE #117: 'EXGLView' has no propType for native prop 'EXGLView.accessibilityLabel' of native type 'String'
Hi, 
Just finished setting up a fresh react native project and successfully linked all libraries for Andriod and IOS I am having this issue on Android and can't seem to figure out the problem. (Works on ios)
screen shot 2017-05-29 at 5 58 07 pm

### PR DESCRIPTION
**Pull request by martykan**
**Summary**

This fixes #117

### CODE REVIEW

**Comment by kelset** [comment]
Can confirm, it fixes it for me.

**Comment by Josephmaxim** [comment]
@kelset I am still getting the same error. did you edit the EXGLView.js under node-modules/gl-react-native/src/EXGLView.js ?

**Comment by martykan** [comment]
@Josephmaxim Did you maybe forget to rebuild with `yarn`?

**Comment by kelset** [comment]
@Josephmaxim yes, I simply did the fix this PR shows.

**Comment by gre** [comment]
can you test if just this way fix the bug: https://github.com/expo/expo-sdk/commit/c443b48de474207b50d39878d9045032b8a3e508#diff-1c7aa597d19b0f204a0404e4b9eee554

i think it's the proper way to fix this bug and we should not diverge much from that GLView.js in that repo ( as it's basically a fork of it ).

**Comment by gre** [comment]
also i'm soon going to import the latest stuff from the EXGL impl.

> (i'm currently a bit off, as i'm traveling around China🤣 back in a week or so)

**Comment by kelset** [comment]
Ok, small update: while trying to fix it the `viewPropTypes` way, as suggested by @gre, I removed & reinstalled the `node_modules`.

Since I couldn't figure out a way to make it work via that approach, I went back to the solution proposed in this PR and... I can't find a way to make it work - I'm in @Josephmaxim situation now.

I think it may be related to properly cleaning up the project, doing  `./gradlew clean` before `react-native run-android`, but still I can't find a way atm. I'll keep trying and let you know how it turns out.

**Comment by Josephmaxim** [comment]
Any updates?

**Comment by kelset** [comment]
Sorry, no updates on my side - I've been using `expo` as a temp workaround to get it to work, but I still haven't found a "final solution". But the mantainer should be back now so I think he can take care of the issue soon :)

**Comment by gre** [comment]
sorry guys, was pretty busy the past weeks (crazy China trip XD), anway, i'm back! going to tackle that in the week

**Comment by aaronbuchanan** [comment]
Welcome back @gre! Hitting this issue as well, the workaround proposed above didn't make a difference for me. Lmk if there's anything I can do to help here

**Comment by kelset** [comment]
I think this PR can be closed since the issue gets fixed by commit 0b502ce

**Pull request closed without merging**
